global:
  resolve_timeout: 5m

route:
  receiver: "slack"
  group_by:
  - alertname
  - namespace
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 2h
  routes:
  - receiver: "null"
    matchers:
    - alertname =~ "InfoInhibitor|Watchdog"

inhibit_rules:
- target_matchers:
  - severity =~ warning|info
  source_matchers:
  - severity = critical
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - severity = warning
  equal:
  - namespace
  - alertname
- target_matchers:
  - severity = info
  source_matchers:
  - alertname = InfoInhibitor
  equal:
  - namespace

receivers:
- name: "slack"
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: '#is-the-server-broken'
    send_resolved: true
    title: '[{{ .Status | toUpper }}:{{ .Alerts.Firing | len }}] {{ .CommonLabels.alertname }}'
    text: |-
      *Severity:* {{ .CommonLabels.severity }}
      *Namespace:* {{ .CommonLabels.namespace }}
      *Description:* {{ .CommonAnnotations.description }}
      *Summary:* {{ .CommonAnnotations.summary }}
      *Runbook:* {{ .CommonAnnotations.runbook_url }}
- name: "null"

templates:
- /etc/alertmanager/config/*.tmpl
