apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-main
  namespace: observability
  labels:
    app: alertmanager
data:
  alertmanager.yml: |
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'
  
    route:
      receiver: 'slack-notifications'
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h
  
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#is-the-server-broken'
        send_resolved: true
