apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-propjoe-references
spec:
  capacity:
    storage: 900Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-propjoe-hdd
  nfs:
    server: propjoe.scripps.edu
    path: "/data/references"
