apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-propjoe-shared
spec:
  capacity:
    storage: 900Ti
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-propjoe-hdd
  nfs:
    server: propjoe.scripps.edu
    path: "/data/brineylab_shared"
