apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-sparrow-workspace
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-sparrow-nvme
  mountOptions:
    - hard
    - proto=tcp
  nfs:
    server: 192.168.1.3 # sparrow.scripps.edu over mlnx
    path: /sparrow_data_zfspool/sparrow_workspace/