apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-stringer-ont
spec:
  capacity:
    storage: 200Ti
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-stringer-hdd
  nfs:
    server: stringer.scripps.edu
    path: "/volume1/ONT"
