apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-wallace-shared
spec:
  capacity:
    storage:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-wallace-shared-nvme
  nfs:
    server: 192.168.1.2 #wallace.scripps.edu over mlnx
    path: "/wallace_data_zfspool/brineylab_shared"
