apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-wallace-shared
spec:
  capacity:
    storage: 300Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-wallace-shared-nvme
  mountOptions:
    - hard
    - proto=tcp
  nfs:
    path: /wallace_data_zfspool/brineylab_shared
    server: 192.168.1.3 #wallace.scripps.edu over mlnx



