apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-wallace-shared
spec:
  capacity:
    storage: 1700Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-wallace-shared
  nfs:
    server: wallace.scripps.edu
    path: "/data/brineylab_shared"
