apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cedric-jh
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: microk8s.io/hostpath
parameters:
  pvDir: /data/jupyterhub
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer