# marlo-sc.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-wallace-jh-nvme
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.3 # wallace.scripps.edu over mlnx
  share: /wallace_data_zfspool/jupyterhub
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - proto=tcp
 # - nfsvers=4.1
# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: nfs-marlo-ssd
# parameters:
#   archiveOnDelete: "true"
# provisioner: cluster.local/nfs-subdir-external-provisioner
# reclaimPolicy: Delete
# volumeBindingMode: Immediate
# allowVolumeExpansion: true
