apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cedric-workspace
  namespace: jupyterhub
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10000Gi
  storageClassName: cedric-workspace
  volumeName: cedric-workspace