apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-wallace-shared
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-wallace-nvme
  volumeName: nfs-wallace-shared
  resources:
    requests:
      storage: 300Ti
