apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-wallance-shared
  namespace: jupyterhub
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-wallance-shared-nvme
  volumeName: nfs-wallance-shared
  resources:
    requests:
      storage: 1700Gi
