apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-wallace-references
  namespace: jupyterhub
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-wallace-nvme
  volumeName: nfs-wallace-references
  resources:
    requests:
      storage: 300Ti 
